frr defaults traditional
hostname 01T1
!
log stdout notifications
log commands
!
no fpm use-next-hop-groups
!
fpm address 127.0.0.1
zebra nexthop-group keep 1
!
ipv6 route fcbb:bbbb:1::/48 2001:db8:1:1001::1 Ethernet0
ipv6 route fcbb:bbbb:2::/48 2001:db8:2:1001::2 Ethernet4
ipv6 route fcbb:bbbb:A001::/48 2001:db8:1:1001::1 Ethernet0
ipv6 route fcbb:bbbb:B001::/48 2001:db8:2:1001::2 Ethernet4
!
segment-routing
 srv6
  locators
   locator MAIN
    prefix fcbb:bbbb:1001::/48
    format usid-f3216
   exit
  exit
  !
  static
   sid fcbb:bbbb:1001::/48 locator MAIN behavior uN
   sid fcbb:bbbb:fe01::/48 locator MAIN behavior uA interface Ethernet0
   sid fcbb:bbbb:1001:fe01::/64 locator MAIN behavior uA interface Ethernet0
   sid fcbb:bbbb:fe02::/48 locator MAIN behavior uA interface Ethernet4
   sid fcbb:bbbb:1001:fe02::/64 locator MAIN behavior uA interface Ethernet4
  exit
  !
  encapsulation
   source-address fcbb:bbbb:1001::1
  exit
 exit
exit
!
ip forwarding
ipv6 forwarding
!
line vty
!
