frr defaults traditional
hostname 02T0
!
log stdout notifications
log commands
!
no fpm use-next-hop-groups
!
fpm address 127.0.0.1
zebra nexthop-group keep 1
!
ipv6 route fcbb:bbbb:1::/48 2001:db8:2:1001::1001 Ethernet4
ipv6 route fcbb:bbbb:1::/48 2001:db8:2:1002::1002 Ethernet8
ipv6 route fcbb:bbbb:1001::/48 2001:db8:2:1001::1001 Ethernet4
ipv6 route fcbb:bbbb:1002::/48 2001:db8:2:1002::1002 Ethernet8
ipv6 route fcbb:bbbb:A001::/48 2001:db8:2:1001::1001 Ethernet4
ipv6 route fcbb:bbbb:A001::/48 2001:db8:2:1002::1002 Ethernet8
ipv6 route fcbb:bbbb:B001::/48 2001:db8:2:B001::B001 Ethernet0
!
segment-routing
 srv6
  locators
   locator MAIN
    prefix fcbb:bbbb:2::/48
    format usid-f3216
   exit
  exit
  !
  static
   sid fcbb:bbbb:2::/48 locator MAIN behavior uN
   sid fcbb:bbbb:fe11::/48 locator MAIN behavior uA interface Ethernet4
   sid fcbb:bbbb:2:fe11::/64 locator MAIN behavior uA interface Ethernet4
   sid fcbb:bbbb:fe12::/48 locator MAIN behavior uA interface Ethernet8
   sid fcbb:bbbb:2:fe12::/64 locator MAIN behavior uA interface Ethernet8
  exit
  !
  encapsulation
   source-address fcbb:bbbb:2::1
  exit
 exit
exit
!
ip forwarding
ipv6 forwarding
!
line vty
!
