frr defaults traditional
hostname 01T1
!
log stdout notifications
log commands
!
no fpm use-next-hop-groups
!
fpm address 127.0.0.1
zebra nexthop-group keep 1
!
router bgp 65011
 bgp router-id 11.11.11.11
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 no bgp network import-check
 bgp bestpath as-path multipath-relax
 neighbor 2001:db8:1:1001::1 remote-as 65001
 neighbor 2001:db8:1:1001::1 timers 3 10
 neighbor 2001:db8:1:1001::1 timers connect 1
 neighbor 2001:db8:1:1001::1 capability extended-nexthop
 neighbor 2001:db8:1:1001::1 disable-connected-check
 neighbor 2001:db8:2:1001::2 remote-as 65002
 neighbor 2001:db8:2:1001::2 timers 3 10
 neighbor 2001:db8:2:1001::2 timers connect 1
 neighbor 2001:db8:2:1001::2 capability extended-nexthop
 neighbor 2001:db8:2:1001::2 disable-connected-check
 !
 address-family ipv6 unicast
  network fcbb:bbbb:1001::/48
  network fcbb:bbbb:1001::1/128
  neighbor 2001:db8:1:1001::1 activate
  neighbor 2001:db8:2:1001::2 activate
 exit-address-family
 !
 address-family ipv6 vpn
  neighbor 2001:db8:1:1001::1 activate
  neighbor 2001:db8:2:1001::2 activate
 exit-address-family
exit
!
segment-routing
 srv6
  locators
   locator MAIN
    prefix fcbb:bbbb:1001::/48
    format usid-f3216
   exit
  exit
  !
  encapsulation
   source-address fcbb:bbbb:1001::1
  exit
 exit
exit
!
ip forwarding
ipv6 forwarding
!
line vty
!
